package ar.com.agtech.syros.esphora.conector.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2012-04-09T09:24:06.287-03:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "Wsfev1Service", 
                  wsdlLocation = "http://ec2-50-17-85-59.compute-1.amazonaws.com:8080/esphora-conector/ws/wsfev1?wsdl",
                  targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/") 
public class Wsfev1Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://servicios.conector.esphora.syntagma.com.ar/", "Wsfev1Service");
    public final static QName Wsfev1Port = new QName("http://servicios.conector.esphora.syntagma.com.ar/", "wsfev1Port");
    static {
        URL url = null;
        try {
            url = new URL("http://ec2-50-17-85-59.compute-1.amazonaws.com:8080/esphora-conector/ws/wsfev1?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Wsfev1Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://ec2-50-17-85-59.compute-1.amazonaws.com:8080/esphora-conector/ws/wsfev1?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Wsfev1Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Wsfev1Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Wsfev1Service() {
        super(WSDL_LOCATION, SERVICE);
    }
 /*   
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Wsfev1Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Wsfev1Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Wsfev1Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }
*/
    /**
     *
     * @return
     *     returns Wsfev1
     */
    @WebEndpoint(name = "wsfev1Port")
    public Wsfev1 getWsfev1Port() {
        return super.getPort(Wsfev1Port, Wsfev1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Wsfev1
     */
    @WebEndpoint(name = "wsfev1Port")
    public Wsfev1 getWsfev1Port(WebServiceFeature... features) {
        return super.getPort(Wsfev1Port, Wsfev1.class, features);
    }

}
