package ar.com.agtech.syros.esphora.conector.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2012-04-09T09:24:06.065-03:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", name = "wsfev1")
@XmlSeeAlso({ar.com.agtech.syros.esphora.conector.artifacts.ObjectFactory.class, ObjectFactory.class})
public interface Wsfev1 {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "FEParamGetTiposDoc", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FEParamGetTiposDoc")
    @WebMethod(operationName = "FEParamGetTiposDoc")
    @ResponseWrapper(localName = "FEParamGetTiposDocResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FEParamGetTiposDocResponse")
    public ar.com.agtech.syros.esphora.conector.artifacts.DocTipoResponse feParamGetTiposDoc(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "FEParamGetPtosVenta", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FEParamGetPtosVenta")
    @WebMethod(operationName = "FEParamGetPtosVenta")
    @ResponseWrapper(localName = "FEParamGetPtosVentaResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FEParamGetPtosVentaResponse")
    public ar.com.agtech.syros.esphora.conector.artifacts.FEPtoVentaResponse feParamGetPtosVenta(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "FECAEARegInformativo", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FECAEARegInformativo")
    @WebMethod(operationName = "FECAEARegInformativo")
    @ResponseWrapper(localName = "FECAEARegInformativoResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FECAEARegInformativoResponse")
    public ar.com.agtech.syros.esphora.conector.artifacts.FECAEAResponse fecaeaRegInformativo(
        @WebParam(name = "feCAEARegInfReq", targetNamespace = "")
        ar.com.agtech.syros.esphora.conector.artifacts.FECAEARequest feCAEARegInfReq,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "FECAESolicitar", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FECAESolicitar")
    @WebMethod(operationName = "FECAESolicitar")
    @ResponseWrapper(localName = "FECAESolicitarResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FECAESolicitarResponse")
    public ar.com.agtech.syros.esphora.conector.artifacts.FECAEResponse fecaeSolicitar(
        @WebParam(name = "fer", targetNamespace = "")
        ar.com.agtech.syros.esphora.conector.artifacts.FECAERequest fer,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "FECAEASinMovimientoConsultar", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FECAEASinMovimientoConsultar")
    @WebMethod(operationName = "FECAEASinMovimientoConsultar")
    @ResponseWrapper(localName = "FECAEASinMovimientoConsultarResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FECAEASinMovimientoConsultarResponse")
    public ar.com.agtech.syros.esphora.conector.artifacts.FECAEASinMovConsResponse fecaeaSinMovimientoConsultar(
        @WebParam(name = "caea", targetNamespace = "")
        java.lang.String caea,
        @WebParam(name = "ptoVta", targetNamespace = "")
        int ptoVta,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "FEParamGetTiposOpcional", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FEParamGetTiposOpcional")
    @WebMethod(operationName = "FEParamGetTiposOpcional")
    @ResponseWrapper(localName = "FEParamGetTiposOpcionalResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FEParamGetTiposOpcionalResponse")
    public ar.com.agtech.syros.esphora.conector.artifacts.OpcionalTipoResponse feParamGetTiposOpcional(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "FECompTotXRequest", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FECompTotXRequest")
    @WebMethod(operationName = "FECompTotXRequest")
    @ResponseWrapper(localName = "FECompTotXRequestResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FECompTotXRequestResponse")
    public ar.com.agtech.syros.esphora.conector.artifacts.FERegXReqResponse feCompTotXRequest(
        @WebParam(name = "caea", targetNamespace = "")
        java.lang.String caea,
        @WebParam(name = "ptoVta", targetNamespace = "")
        int ptoVta,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "FECAEASolicitar", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FECAEASolicitar")
    @WebMethod(operationName = "FECAEASolicitar")
    @ResponseWrapper(localName = "FECAEASolicitarResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FECAEASolicitarResponse")
    public ar.com.agtech.syros.esphora.conector.artifacts.FECAEAGetResponse fecaeaSolicitar(
        @WebParam(name = "periodo", targetNamespace = "")
        int periodo,
        @WebParam(name = "orden", targetNamespace = "")
        short orden,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "FEParamGetTiposConcepto", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FEParamGetTiposConcepto")
    @WebMethod(operationName = "FEParamGetTiposConcepto")
    @ResponseWrapper(localName = "FEParamGetTiposConceptoResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FEParamGetTiposConceptoResponse")
    public ar.com.agtech.syros.esphora.conector.artifacts.ConceptoTipoResponse feParamGetTiposConcepto(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "FEParamGetTiposCbte", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FEParamGetTiposCbte")
    @WebMethod(operationName = "FEParamGetTiposCbte")
    @ResponseWrapper(localName = "FEParamGetTiposCbteResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FEParamGetTiposCbteResponse")
    public ar.com.agtech.syros.esphora.conector.artifacts.CbteTipoResponse feParamGetTiposCbte(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "FEParamGetTiposTributo", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FEParamGetTiposTributo")
    @WebMethod(operationName = "FEParamGetTiposTributo")
    @ResponseWrapper(localName = "FEParamGetTiposTributoResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FEParamGetTiposTributoResponse")
    public ar.com.agtech.syros.esphora.conector.artifacts.FETributoResponse feParamGetTiposTributo(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "FEParamGetTiposMonedas", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FEParamGetTiposMonedas")
    @WebMethod(operationName = "FEParamGetTiposMonedas")
    @ResponseWrapper(localName = "FEParamGetTiposMonedasResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FEParamGetTiposMonedasResponse")
    public ar.com.agtech.syros.esphora.conector.artifacts.MonedaResponse feParamGetTiposMonedas(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "FECAEASinMovimientoInformar", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FECAEASinMovimientoInformar")
    @WebMethod(operationName = "FECAEASinMovimientoInformar")
    @ResponseWrapper(localName = "FECAEASinMovimientoInformarResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FECAEASinMovimientoInformarResponse")
    public ar.com.agtech.syros.esphora.conector.artifacts.FECAEASinMovResponse fecaeaSinMovimientoInformar(
        @WebParam(name = "caea", targetNamespace = "")
        java.lang.String caea,
        @WebParam(name = "ptoVta", targetNamespace = "")
        int ptoVta,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "FEParamGetTiposIva", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FEParamGetTiposIva")
    @WebMethod(operationName = "FEParamGetTiposIva")
    @ResponseWrapper(localName = "FEParamGetTiposIvaResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FEParamGetTiposIvaResponse")
    public ar.com.agtech.syros.esphora.conector.artifacts.IvaTipoResponse feParamGetTiposIva(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "FECompUltimoAutorizado", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FECompUltimoAutorizado")
    @WebMethod(operationName = "FECompUltimoAutorizado")
    @ResponseWrapper(localName = "FECompUltimoAutorizadoResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FECompUltimoAutorizadoResponse")
    public ar.com.agtech.syros.esphora.conector.artifacts.FERecuperaLastCbteResponse feCompUltimoAutorizado(
        @WebParam(name = "tipoComprobante", targetNamespace = "")
        int tipoComprobante,
        @WebParam(name = "puntoVenta", targetNamespace = "")
        int puntoVenta,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "FEParamGetCotizacion", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FEParamGetCotizacion")
    @WebMethod(operationName = "FEParamGetCotizacion")
    @ResponseWrapper(localName = "FEParamGetCotizacionResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FEParamGetCotizacionResponse")
    public ar.com.agtech.syros.esphora.conector.artifacts.FECotizacionResponse feParamGetCotizacion(
        @WebParam(name = "monId", targetNamespace = "")
        java.lang.String monId,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "FECAEAConsultar", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FECAEAConsultar")
    @WebMethod(operationName = "FECAEAConsultar")
    @ResponseWrapper(localName = "FECAEAConsultarResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FECAEAConsultarResponse")
    public ar.com.agtech.syros.esphora.conector.artifacts.FECAEAGetResponse fecaeaConsultar(
        @WebParam(name = "periodo", targetNamespace = "")
        int periodo,
        @WebParam(name = "orden", targetNamespace = "")
        short orden,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "FECompConsultar", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FECompConsultar")
    @WebMethod(operationName = "FECompConsultar")
    @ResponseWrapper(localName = "FECompConsultarResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FECompConsultarResponse")
    public ar.com.agtech.syros.esphora.conector.artifacts.FECompConsultaResponse feCompConsultar(
        @WebParam(name = "FECompConsultaReq", targetNamespace = "")
        ar.com.agtech.syros.esphora.conector.artifacts.FECompConsultaReq feCompConsultaReq,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "FEV1Dummy", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FEV1Dummy")
    @WebMethod(operationName = "FEV1Dummy")
    @ResponseWrapper(localName = "FEV1DummyResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.agtech.syros.esphora.conector.services.FEV1DummyResponse")
    public ar.com.agtech.syros.esphora.conector.artifacts.DummyResponse fev1Dummy(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit
    );
}
